### ISSUE TITLE
Where to find the file "relations_fr.jsonl"

### ISSUE THREAD

**Issue by lixin4ever** [norakassner/mlama#3]
Thank you for your great work.

I followed the instructions in README to run some experiments on your multilingual lama benchmark but encountered the FileNotFoundError. I wonder where to find the file `./data/TREx_multilingual/templates/relations_fr.jsonl`? Did you forget to upload such relation files?

**Comment by norakassner** [comment]
Sorry about that! We changed the dataset structure and forgot to adapt the path. It should be fixed now.
