### ISSUE TITLE
How do you implement cross-lingual pooling？

### ISSUE THREAD

**Issue by uziyyds** [norakassner/mlama#4]
There is no detailed description in the paper of cross-lingual pooling, can you explain it or tell me where the code is.

**Comment by norakassner** [comment]
Hi, the pooling experiments are not part of the repo. But let me give you some details as it is easy to implement: For each test instance we collect the first-ranked candidate for all languages we have templates of. Then we translate these predictions to English. Finally, the most prediction with highest occurrence is select. Let me know if you have any further doubts!
