### ISSUE TITLE
RuntimeError: cannot join current thread when trying to move model to CUDA

### ISSUE THREAD

**Issue by kg16** [norakassner/mlama#7]
On executing `python scripts/run_experiments_mBERT_ranked.py --lang "en"` the run fails with the following error:

`Loading bert model...
distinct template facts: 936
  0%|                                                                                                                               | 0/234 [00:00<?, ?it/s]
Moving model to CUDA
Traceback (most recent call last): 
..........
[logs_mlama_cuda error.txt](https://github.com/norakassner/mlama/files/8666312/logs_mlama_cuda.error.txt)

    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
`
Attaching detailed logs, and nvidia-smi output in the .txt file. Please let me know if you encountered these while running experiments and have a resolution.

Thanks.

**Comment by kg16** [comment]
Trying to run on different machine

**Comment by norakassner** [comment]
I have only run the code on an cpu machine. So it might very well be that it is not working on gpu. I will double check on my setup later but won't be have time to do any debugging in the near future. If it only runs on cpu right now, I will indicate that in the code and will fix it at a later point.
