### ISSUE TITLE
License

### ISSUE THREAD

**Issue by muelletm** [norakassner/mlama#8]
Hi!

Thanks a lot for creating this dataset and making it available.
Could you add a license file for the code and data so that this can be used by industry labs?
Maybe the data license is just inherited from the underlying data but maybe that could be made explicit.

**Comment by pdufter** [comment]
Hi @muelletm thanks for raising this question. We will add license information shortly.

**Comment by norakassner** [comment]
Hi @muelletm sorry for the delay. We followed the licensing of the initial LAMA data which unfortunately is non commercial.
